[OGrEE-3D]
verbose = true
fullscreen = false
cachePath = "C:/"
cacheLimitMo = 100
cliPort = 5500
alphaOnInteract = 50

[OGrEE-3D.textures]
perf22 = "https://raw.githubusercontent.com/ditrit/OGREE-3D/master/Assets/Resources/Textures/TilePerf22.png"
perf29 = "https://raw.githubusercontent.com/ditrit/OGREE-3D/master/Assets/Resources/Textures/TilePerf29.png"
elesh  = "https://static.wikia.nocookie.net/mtgsalvation_gamepedia/images/1/13/Elesh_Norn.jpg/revision/latest?cb=20210216024711"

[OGrEE-3D.colors]
selection = "#21FF00"
edit = "#C900FF"
focus = "#FF9F00"
highlight = "#00D5FF"

usableZone = "#DBEDF2"
reservedZone = "#F2F2F2"
technicalZone = "#EBF2DE"

[OGrEE-3D.temperature]
minC = 0
maxC = 100
minF = 32
maxF = 212

useCustomGradient = true
customTemperatureGradient = [
    [0,0,255,0],
    [255,0,0,100],
    [255,255,0,50]
]
