[OGrEE-3D]
verbose = true
fullscreen = false
cachePath = "C:/"
cacheLimitMo = 100
# Port used to receive messages from OGrEE-CLI. 5500 by default
cliPort = 5500
# Value clamped from 0 to 100
alphaOnInteract = 50
# Value clamped from 0.01 to 1, 0.25 by default
doubleClickDelay = 0.25

# Camera settings
# Value clamped from 1 to 50, 15 by default
moveSpeed = 15
# Value clamped from 1 to 100, 50 by default
rotationSpeed = 50
# Height of the camera in "Human mode movement". Clamped from 1.5 to 1.8, 1.62 by default
humanHeight = 1.62

[OGrEE-3D.textures]
# Textures loaded in the 3D client at startup, in "name = url" format
perf22 = "https://raw.githubusercontent.com/ditrit/OGREE-3D/master/Assets/Resources/Textures/TilePerf22.png"
perf29 = "https://raw.githubusercontent.com/ditrit/OGREE-3D/master/Assets/Resources/Textures/TilePerf29.png"

[OGrEE-3D.colors]
# Colors can be defines with hexadecimal codes or html colors
# Strings that do not begin with '#' will be parsed as literal colors, with the following supported:
# red, cyan, blue, darkblue, lightblue, purple, yellow, lime, fuchsia, white, silver, grey, black, orange, brown, maroon, green, olive, navy, teal, aqua, magenta..
selection = "#21FF00"
edit = "#C900FF"
focus = "#FF9F00"
highlight = "#00D5FF"
scatterPlot = "#2C4CBE"

usableZone = "#DBEDF2"
reservedZone = "#F2F2F2"
technicalZone = "#EBF2DE"

[OGrEE-3D.temperature]
# Minimum and maximum values for temperatures in Celsius and Fahrenheit to define the range of the temperature gradients
minC = 0
maxC = 100
minF = 32
maxF = 212

# Define a custom gradient by defining up to 8 colors in rgb format with a fourth parameter specifying the position of the color in the gradient (rgb from 0 to 255, position from 0 to 100)
useCustomGradient = true
customTemperatureGradient = [
    [0,0,255,0],
    [0,255,255,30],
    [0,255,0,50],
    [255,255,0,70],
    [255,0,0,100]
]
